version: '3.5'

services:
  shinyproxy:
    build:
      context: ./shinyproxy
      dockerfile: Dockerfile
    restart: 'unless-stopped'
    networks:
      - shinystudio-net
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
      - USERID=${USERID}
      - USER=${USER}
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - "127.0.0.1:${SITEPORT}:8080"

  rstudio_rshiny_vscode:
    build:
      context: ./rstudio_rshiny_vscode
      dockerfile: Dockerfile
    restart: 'no'
    networks:
      - shinystudio-net
    ports:
      - '8787:8787'
      - '8888:8888'
      - '3838:3838'
      - '8443:8443'
    volumes:
      - "${MOUNTPOINT}/content/sites/${DESTSITE}:/home/${USER}/__ShinyStudio__:z"
      - "${MOUNTPOINT}/content/users/${USER}:/home/${USER}/__Personal__:z"
      # - "${MOUNTPOINT}/logs/${DESTSITE}/${USER}:/var/log/shiny-server:z"
      - "${MOUNTPOINT}/settings/rstudio/${USER}/user-settings:/home/${USER}/.rstudio/monitored/user-settings:z"
      - "${MOUNTPOINT}/settings/vscode/${USER}:/home/${USER}/.local/share/code-server/User:z"
      - 'r_libraries:/r-libs'
      - 'py_environment:/pyenv'
      - "pwsh_modules:/home/${USER}/.local/share/powershell/Modules"
    environment:
      - USER=${USER}
      - USERID=${USERID}

volumes:
  r_libraries:
  py_environment:
  pwsh_modules:

networks:
  shinystudio-net:
    name: shinystudio-net
  default:
     external:
      name: shinystudio-net
